<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NeighbourhoodDescriptionSeeder extends Seeder
{
    public function run(): void
    {
        $descriptions = [
            // ── Surrey ──────────────────────────────────────────────────────────
            [
                'place' => 'Fleetwood Tynehead',
                'city'  => 'Surrey',
                'description' => 'Fleetwood is one of Surrey\'s most family-friendly and rapidly growing neighbourhoods, situated in the northeast part of the city. The area offers a diverse mix of real estate including detached single-family homes, townhouses, and a growing number of condos. Fleetwood is well-served by the 152nd Street and 88th Avenue corridors, with easy access to Highway 1 and the Golden Ears Bridge. Families are drawn to the neighbourhood for its excellent schools, spacious parks, and the Fleetwood Community Centre. The upcoming SkyTrain extension along Fraser Highway is expected to further boost property values and transit connectivity. With a blend of established quiet streets and new master-planned communities, Fleetwood appeals to first-time buyers, upsizing families, and investors looking for strong long-term growth potential in the Metro Vancouver market.',
            ],
            [
                'place' => 'Newton',
                'city'  => 'Surrey',
                'description' => 'Newton is a vibrant, multicultural neighbourhood at the heart of Surrey, BC, known for its incredible diversity and strong sense of community. The area features a broad spectrum of housing options, from affordable condos and townhouses to spacious detached homes on large lots. Newton\'s central location provides residents with quick access to Scott Road, King George Boulevard, and the Newton Exchange transit hub, making commutes throughout Metro Vancouver straightforward. The neighbourhood is home to Newton Athletic Park, Bear Creek Park, and numerous community centres that serve its large and active population. Shopping, dining, and services along 72nd Avenue and King George Boulevard offer everyday convenience. Newton continues to attract first-time buyers and growing families who value affordability, accessibility, and the rich cultural fabric of one of Surrey\'s most established communities.',
            ],
            [
                'place' => 'Whalley',
                'city'  => 'Surrey',
                'description' => 'Whalley, also known as the City Centre of Surrey, is undergoing a dramatic transformation into a modern urban hub in Metro Vancouver. The neighbourhood surrounds the King George SkyTrain station and Surrey Central station, making it one of the most transit-connected communities in the region. High-rise condos and mixed-use developments are reshaping the skyline, offering buyers and investors access to new construction at prices well below comparable Vancouver neighbourhoods. Whalley is home to SFU Surrey, Surrey City Hall, Central City Shopping Centre, and a rapidly expanding healthcare district. The area attracts students, young professionals, and investors seeking high rental demand and long-term appreciation. With billions of dollars in planned infrastructure investment, Whalley represents one of the most compelling real estate opportunities in the Greater Vancouver area.',
            ],
            [
                'place' => 'Cloverdale',
                'city'  => 'Surrey',
                'description' => 'Cloverdale is a charming historic town centre neighbourhood in the southeast corner of Surrey, BC, offering a unique blend of small-town character and modern suburban living. Known for its heritage downtown, the Cloverdale Rodeo, and the Cloverdale Fairgrounds, this community has a distinct identity that sets it apart from other Surrey neighbourhoods. Real estate in Cloverdale features a strong selection of detached single-family homes, many with large lots, alongside newer townhouse developments that appeal to families and downsizers. The neighbourhood benefits from easy access to Highway 10 and Highway 15, connecting residents to Langley, White Rock, and the US border. Cloverdale is popular with families who want more space and a quieter lifestyle without sacrificing proximity to Metro Vancouver\'s job centres and amenities.',
            ],
            [
                'place' => 'Guildford',
                'city'  => 'Surrey',
                'description' => 'Guildford is a well-established and highly convenient neighbourhood in north Surrey, BC, anchored by the Guildford Town Centre mall and surrounded by excellent transit connections. The area serves as a major retail and service hub for northeastern Surrey, with bus routes linking residents to Scott Road and King George SkyTrain stations. Real estate in Guildford ranges from affordable apartment condos and townhouses to detached single-family homes on quiet residential streets. The neighbourhood appeals strongly to families, thanks to its numerous parks, recreation facilities, and proximity to top-rated schools. Green spaces such as Holland Park are within easy reach, offering outdoor amenities for all ages. Guildford\'s combination of shopping convenience, transit access, and comparatively affordable housing makes it a perennially popular choice for first-time buyers and growing families in the Metro Vancouver market.',
            ],
            [
                'place' => 'Sullivan Station',
                'city'  => 'Surrey',
                'description' => 'Sullivan Station is a modern, master-planned community in the eastern part of Surrey, BC, developed primarily in the 2000s and known for its well-organized street grid, attractive townhomes, and family-oriented character. The neighbourhood offers a strong mix of detached single-family homes, townhouses, and low-rise condos, appealing to a wide range of buyers. Sullivan Station residents enjoy proximity to Sullivan Heights Secondary School, several community parks, and the Sullivan Recreation Centre. The area provides convenient access to Highway 10 and the King George Boulevard corridor, connecting residents to Cloverdale, Newton, and beyond. Bus rapid transit and future SkyTrain expansion plans further bolster the neighbourhood\'s long-term connectivity. Sullivan Station is consistently popular with young families seeking a safe, walkable community with newer housing stock and good value relative to the broader Metro Vancouver real estate market.',
            ],
            [
                'place' => 'Panorama Ridge',
                'city'  => 'Surrey',
                'description' => 'Panorama Ridge is a prestigious residential neighbourhood in south Surrey, BC, known for its elevated terrain, panoramic views of the Fraser Valley, and generous lot sizes. The area is dominated by executive-style detached single-family homes, many featuring large yards and high-end finishes that attract established families and move-up buyers. Panorama Ridge offers a quieter, more rural atmosphere compared to other Surrey communities, yet remains well connected via 152nd Street and Highway 10 to shopping, schools, and transit hubs. Panorama Ridge Secondary School and several elementary schools serve the neighbourhood\'s strong family population. Green spaces and walking trails are abundant, reflecting the community\'s appreciation for an active outdoor lifestyle. The combination of spacious properties, scenic surroundings, and convenient access to both South Surrey amenities and the border crossing makes Panorama Ridge one of Surrey\'s most sought-after upscale residential communities.',
            ],
            [
                'place' => 'Fraser Heights',
                'city'  => 'Surrey',
                'description' => 'Fraser Heights is one of Surrey\'s most desirable upscale neighbourhoods, situated in the northwest corner of the city on a plateau overlooking the Fraser River. Developed largely in the 1990s, the community is known for its spacious executive homes, winding tree-lined streets, and strong sense of neighbourhood pride. Real estate in Fraser Heights consists primarily of detached single-family homes ranging from well-maintained older builds to contemporary custom residences. Fraser Heights Secondary School and several sought-after elementary schools make the area a magnet for families prioritizing education. The neighbourhood provides easy access to Highway 1, the Port Mann Bridge, and the Pattullo Bridge, making commutes to Burnaby, Vancouver, and Coquitlam manageable. With its quiet residential character, generous lot sizes, and proximity to parks and recreational amenities, Fraser Heights consistently ranks among Surrey\'s top choices for families seeking space, quality, and community.',
            ],
            [
                'place' => 'Morgan Creek',
                'city'  => 'Surrey',
                'description' => 'Morgan Creek is an exclusive gated and semi-gated community in south Surrey, BC, built around the Morgan Creek Golf Course and widely regarded as one of the most prestigious residential addresses in the Fraser Valley. The neighbourhood features an impressive array of luxury single-family homes, including custom-built estates, executive residences, and elegant half-duplexes catering to discerning buyers. Manicured streetscapes, extensive green belts, and proximity to Sunnyside Acres Urban Forest Park give Morgan Creek an upscale resort-like quality year-round. Residents benefit from easy access to 32nd Avenue, Highway 99, and the growing amenities of South Surrey\'s Morgan Crossing and Grandview Corners shopping districts. Morgan Creek appeals to affluent families, retirees, and professionals seeking privacy, luxury finishes, and a premium lifestyle within a well-managed community in South Surrey.',
            ],
            [
                'place' => 'Grandview Surrey',
                'city'  => 'Surrey',
                'description' => 'Grandview Surrey is a rapidly developing master-planned urban district in the south end of Surrey, BC, centred around the Grandview Corners and Morgan Crossing shopping and lifestyle destinations. The neighbourhood has seen significant growth in high-rise and mid-rise condo towers, townhomes, and mixed-use developments, attracting young professionals, downsizers, and investors seeking modern new construction. Grandview Surrey is designed with walkability in mind, featuring wide boulevards, retail at grade, and proximity to restaurants, gyms, grocery stores, and professional services. Highway 99 provides quick access to downtown Vancouver, the Massey Tunnel, and the US border. Future transit improvements and the growing employment base in South Surrey make Grandview a compelling option for buyers who want urban amenities with a suburban scale and price point relative to Vancouver proper.',
            ],
            [
                'place' => 'Bear Creek Green Timbers',
                'city'  => 'Surrey',
                'description' => 'Bear Creek Green Timbers is a well-established, centrally located neighbourhood in Surrey, BC, best known for the sprawling Bear Creek Park — one of the region\'s premier recreational green spaces offering sports fields, picnic areas, a waterpark, and extensive walking trails. The neighbourhood\'s real estate mix includes a healthy blend of detached single-family homes, townhouses, and low-rise apartment condos, making it accessible to a wide range of buyers. 88th Avenue and King George Boulevard provide efficient transit and road connections to Newton, Whalley, and beyond. A strong community infrastructure of schools, neighbourhood centres, and parks makes Bear Creek Green Timbers particularly popular with young families. The area\'s relative affordability compared to other Surrey communities and central location within the city make it a consistently attractive option for first-time buyers looking to enter the Surrey real estate market.',
            ],
            [
                'place' => 'Bridgeview',
                'city'  => 'Surrey',
                'description' => 'Bridgeview is a compact and affordable neighbourhood on the north side of Surrey, BC, situated alongside the Fraser River between Scott Road and the Pattullo Bridge. The area is characterized by a mix of older detached homes, small lots, and a handful of newer infill properties, offering some of the most accessible entry-level real estate in the Metro Vancouver market. Bridgeview\'s proximity to Scott Road SkyTrain station provides excellent transit access to New Westminster, Burnaby, and downtown Vancouver. The neighbourhood has a strong blue-collar heritage and a close-knit community feel, with residents benefiting from nearby services along Scott Road. While Bridgeview is more modest in character than other Surrey neighbourhoods, its location, affordability, and transit access make it an increasingly attractive option for first-time buyers and investors seeking value close to the SkyTrain network.',
            ],
            [
                'place' => 'Strawberry Hill',
                'city'  => 'Surrey',
                'description' => 'Strawberry Hill is a well-established residential neighbourhood in northeast Surrey, BC, offering a family-friendly environment with a mix of detached homes, townhouses, and some low-rise condos. The neighbourhood is served by Scott Road and 96th Avenue, providing residents with straightforward access to Gateway and Scott Road SkyTrain stations and the broader Metro Vancouver transit network. Strawberry Hill is close to Green Timbers Ecological Reserve, a beloved urban forest offering trails, wildlife habitat, and a peaceful escape from the urban environment. A range of local elementary and secondary schools, as well as community recreational facilities, serve the neighbourhood\'s predominantly family demographic. Strawberry Hill\'s combination of relative affordability, transit connectivity, and green space access positions it as a practical and appealing choice for families and investors within the northeast Surrey real estate market.',
            ],
            [
                'place' => 'Bolivar Heights',
                'city'  => 'Surrey',
                'description' => 'Bolivar Heights is a quiet, mid-elevation residential neighbourhood in north Surrey, BC, offering a calmer suburban atmosphere compared to the higher-density areas closer to the SkyTrain corridor. The community features a mix of older detached homes, split-levels, and newer infill developments on established tree-lined streets. Residents benefit from proximity to Highway 1 and easy access to Guildford, Whalley, and North Delta. Local schools, parks, and community amenities serve the neighbourhood\'s primarily family-oriented population. The area is within driving distance of the Guildford Town Centre and various commercial nodes along 108th Avenue, providing everyday convenience without the density of nearby urban centres. Bolivar Heights appeals to buyers seeking detached home ownership in a established Surrey neighbourhood with solid long-term value and the space and quiet that many suburban families prioritize.',
            ],
            [
                'place' => 'Port Kells',
                'city'  => 'Surrey',
                'description' => 'Port Kells is a largely rural and semi-industrial neighbourhood in the northeastern corner of Surrey, BC, bordering Langley and situated near the Golden Ears Bridge interchange. Unlike most other Surrey communities, Port Kells is characterized by acreage properties, hobby farms, light industrial land, and large-lot single-family homes, making it distinctly different in character from the rest of the city. The neighbourhood attracts buyers seeking land, privacy, and the opportunity for agricultural or equestrian uses that are simply unavailable in more urbanized parts of Surrey. Highway 1 access is excellent via the Golden Ears Bridge, connecting Port Kells to the Tri-Cities and Maple Ridge. While public transit service is limited, the area\'s spacious properties and development potential make it appealing to investors, acreage buyers, and those seeking a rural lifestyle within the bounds of Metro Vancouver.',
            ],
            [
                'place' => 'Crescent Beach Ocean Park',
                'city'  => 'Surrey',
                'description' => 'Crescent Beach Ocean Park is one of South Surrey\'s most beloved and scenic neighbourhoods, situated along the shores of Boundary Bay and offering a relaxed, beachside lifestyle rarely found this close to Metro Vancouver. Crescent Beach itself is a charming village with heritage cottages, beach access, restaurants, and a marina that draws residents and visitors year-round. Ocean Park offers a broader mix of real estate including established detached family homes, luxury custom-builds, and modest cottages, all within walking distance of the ocean. The neighbourhood is connected to the rest of South Surrey via King George Boulevard and Highway 99, and is minutes from White Rock\'s oceanfront promenade. Crescent Beach Ocean Park is consistently sought after by families, retirees, and buyers looking for a premium coastal lifestyle at a somewhat more accessible price point than White Rock proper.',
            ],
            [
                'place' => 'South Surrey',
                'city'  => 'Surrey',
                'description' => 'South Surrey is one of the most prestigious and rapidly growing districts within the City of Surrey, BC, encompassing a collection of upscale communities including Ocean Park, Elgin, Hazelmere, and the emerging Grandview Surrey urban centre. The area is defined by its spacious single-family homes, large estate lots, executive townhomes, and a growing selection of modern condos catering to downsizers and young professionals. South Surrey\'s retail corridor along 32nd Avenue and Highway 99 includes South Point Exchange, Morgan Crossing, and Grandview Corners — three of the region\'s premier open-air lifestyle centres. Residents enjoy easy access to Crescent Beach, Elgin Heritage Park, and numerous golf courses. Highway 99 provides a quick connection to downtown Vancouver and the US border crossing at Peace Arch. South Surrey consistently attracts affluent families, retirees, and lifestyle-focused buyers seeking space, quality schools, and a premium suburban living experience.',
            ],
            [
                'place' => 'King George Corridor',
                'city'  => 'Surrey',
                'description' => 'King George Corridor is a major arterial neighbourhood stretching along the King George Boulevard spine in south Surrey, BC, linking Whalley in the north to White Rock in the south. The corridor is home to a diverse mix of real estate, including high-rise condos near the King George SkyTrain station, mid-rise apartment buildings, townhouse developments, and established detached homes as you move south. This transit-rich strip offers buyers a range of entry points into the Surrey market at varying price points. Key amenities including shopping centres, medical offices, community services, and parks are distributed along its length. The King George SkyTrain station anchors the northern end with direct Expo Line service to New Westminster, Burnaby, and downtown Vancouver. The corridor continues to attract investment and redevelopment activity, making it a strategically important real estate zone in South Surrey\'s evolving urban fabric.',
            ],
            [
                'place' => 'Elgin Chantrell',
                'city'  => 'Surrey',
                'description' => 'Elgin Chantrell is one of South Surrey\'s most exclusive residential communities, known for its large estate homes, equestrian properties, and lush, forested surroundings. Developed primarily in the 1980s and 1990s, the neighbourhood features sprawling detached homes on generous lots, many situated along quiet cul-de-sacs and backing onto Elgin Heritage Park and the Nicomekl River. The area is home to some of the finest custom-built residences in all of Surrey, attracting high-net-worth buyers seeking privacy, prestige, and proximity to nature. Elgin Park Secondary School and Chantrell Creek Elementary serve the neighbourhood\'s strong family demographic. Highway 99 and 16th Avenue provide efficient connections to the US border, White Rock, and the broader South Surrey commercial district. Elgin Chantrell represents the pinnacle of the South Surrey lifestyle, combining estate-scale living with natural beauty and strong community values.',
            ],

            // ── Burnaby ─────────────────────────────────────────────────────────
            [
                'place' => 'Metrotown',
                'city'  => 'Burnaby',
                'description' => 'Metrotown is Burnaby\'s premier urban centre and one of Metro Vancouver\'s most dynamic real estate markets. Anchored by Metropolis at Metrotown — the largest shopping mall in BC — and served by the Metrotown and Patterson SkyTrain stations on the Expo Line, the neighbourhood offers exceptional transit connectivity to downtown Vancouver and beyond. The Metrotown real estate market is dominated by high-rise condos, ranging from studios and one-bedroom units ideal for young professionals to larger suites suited for families and downsizers. Its walkable, urban environment, abundance of restaurants, services, and entertainment options make it one of the most liveable communities in the Lower Mainland. Investors are drawn to Metrotown for its strong rental demand driven by proximity to BCIT, Simon Fraser University, and major employment hubs.',
            ],
            [
                'place' => 'Brentwood Park',
                'city'  => 'Burnaby',
                'description' => 'Brentwood Park is one of Burnaby\'s most transformed neighbourhoods, experiencing a dramatic high-rise development boom centred around the Brentwood Town Centre SkyTrain station on the Millennium Line. The area is home to The Amazing Brentwood, a massive mixed-use development reshaping the skyline with residential towers, retail, dining, and entertainment. Real estate in Brentwood Park consists predominantly of new and pre-sale high-rise condos attracting young professionals, investors, and transit-oriented buyers. The neighbourhood\'s Expo Line and Millennium Line connections provide rapid access to downtown Vancouver, SFU, BCIT, and the Tri-Cities. Brentwood Park also retains pockets of established single-family homes and townhouses on the periphery of the transit node, offering some entry-level ground-oriented options. With continued development momentum and strong rental demand, Brentwood Park is one of Burnaby\'s most active and compelling real estate markets.',
            ],
            [
                'place' => 'Burnaby Lake',
                'city'  => 'Burnaby',
                'description' => 'Burnaby Lake is a peaceful residential neighbourhood in the geographic centre of Burnaby, BC, situated alongside the Burnaby Lake Regional Park — a stunning 350-hectare nature reserve offering kayaking, birdwatching, and extensive trail networks. The neighbourhood features a relaxed, green character with a mix of established detached single-family homes, older townhouses, and some low-rise condos tucked into quiet, tree-lined streets. Burnaby Lake\'s real estate market tends to attract nature-loving families and buyers seeking a quieter community feel within Burnaby. The neighbourhood is well connected via Lougheed Highway and Cariboo Road, with bus transit linking residents to Lougheed Town Centre and Production Way SkyTrain stations. Its balance of natural amenity, central Burnaby location, and relatively more spacious properties compared to higher-density corridors makes Burnaby Lake a consistently appealing choice for families and active lifestyle buyers.',
            ],
            [
                'place' => 'Capitol Hill BN',
                'city'  => 'Burnaby',
                'description' => 'Capitol Hill is one of Burnaby\'s most established and sought-after hillside neighbourhoods, offering sweeping views of Burrard Inlet, the North Shore mountains, and downtown Vancouver from its elevated vantage point. The neighbourhood is characterized by well-maintained detached single-family homes, many on large lots with significant panoramic view value that commands premium prices in the Burnaby real estate market. Tree-lined streets, proximity to Confederation Park and its outdoor pool and community centre, and a quiet residential atmosphere make Capitol Hill particularly attractive to families and established buyers. The neighbourhood is connected by bus transit to Holdom and Production Way SkyTrain stations, with convenient road access to Hastings Street and Highway 1. Capitol Hill\'s combination of views, established character, and quality housing stock makes it one of Burnaby\'s most desirable addresses for families and long-term homeowners.',
            ],
            [
                'place' => 'Central Burnaby',
                'city'  => 'Burnaby',
                'description' => 'Central Burnaby is a strategically located residential district in the heart of Burnaby, BC, offering convenient access to multiple SkyTrain lines, major commercial corridors, and the natural amenities of Burnaby Mountain and Burnaby Lake Regional Park. The neighbourhood features a blend of detached single-family homes, older apartment buildings, townhouses, and newer condo developments that collectively serve a broad range of buyer profiles. Willingdon Avenue and Kingsway are the primary commercial arteries, providing everyday retail, dining, and services. Central Burnaby is well served by the Expo Line and Millennium Line, making it a favourite for transit-dependent commuters working in downtown Vancouver or the Tri-Cities. SFU Burnaby Mountain and BCIT are accessible by bus from the neighbourhood, sustaining strong rental demand from students and academic professionals. Central Burnaby offers solid real estate value within one of Metro Vancouver\'s most well-connected mid-city communities.',
            ],
            [
                'place' => 'Deer Lake',
                'city'  => 'Burnaby',
                'description' => 'Deer Lake is one of Burnaby\'s most picturesque and culturally rich neighbourhoods, centred around the beautiful Deer Lake Park and its famous arts and cultural precinct. The Shadbolt Centre for the Arts, Burnaby Village Museum, Burnaby Art Gallery, and the scenic Deer Lake foreshore are all within the neighbourhood, giving it a distinctive character unlike any other Burnaby community. Real estate in Deer Lake is dominated by established detached single-family homes on tree-lined streets, often attracting affluent families and downsizers who value the neighbourhood\'s natural beauty and cultural offerings. The area is generally quieter and more residential in nature than the transit-oriented corridors, with road access via Royal Oak and Sperling avenues connecting residents to Metrotown and Highway 1. Deer Lake\'s unique combination of parkland, arts amenities, and quality housing makes it a perennially desirable Burnaby neighbourhood.',
            ],
            [
                'place' => 'Sperling-Duthie',
                'city'  => 'Burnaby',
                'description' => 'Sperling-Duthie is a well-established residential neighbourhood in north Burnaby, BC, offering a quiet suburban atmosphere with convenient access to SFU Burnaby Mountain, Burnaby Mountain Golf Course, and the Burnaby Mountain Conservation Area. The neighbourhood is characterized by a mix of older detached single-family homes, split-level properties, and some low-rise condos along main arterials. Residents enjoy proximity to Confederation Park and its recreation facilities, including an outdoor pool and sports fields. Lougheed Highway and Hastings Street provide efficient road connections to New Westminster, Coquitlam, and downtown Vancouver, while bus transit links the neighbourhood to Production Way SkyTrain station. Sperling-Duthie appeals to families and buyers seeking a low-key, green community environment within Burnaby, with solid detached home ownership opportunities at pricing generally more accessible than Burnaby\'s transit-heavy urban nodes.',
            ],
            [
                'place' => 'Forest Hills BN',
                'city'  => 'Burnaby',
                'description' => 'Forest Hills is a quiet, forested neighbourhood in north Burnaby, BC, nestled on the slopes of Burnaby Mountain and known for its spacious single-family homes, mature tree canopy, and exceptional access to outdoor recreation. The neighbourhood borders the SFU Burnaby Mountain campus and the Burnaby Mountain Conservation Area, making it a favourite among academics, nature lovers, and families who prioritize green space and a peaceful residential setting. Homes in Forest Hills tend to be larger detached properties on generous lots, often with partial mountain or city views, making them among the more distinctive and desirable in north Burnaby. Road access via Gaglardi Way and Hastings Street connects residents to Coquitlam, New Westminster, and the Trans-Canada Highway. Forest Hills offers a rare combination of mountain proximity, academic community ties, and quiet suburban living within the City of Burnaby.',
            ],

            // ── Vancouver ────────────────────────────────────────────────────────
            [
                'place' => 'Yaletown',
                'city'  => 'Vancouver',
                'description' => 'Yaletown is one of Vancouver\'s most sought-after inner-city neighbourhoods, renowned for its converted warehouse lofts, boutique restaurants, and vibrant waterfront lifestyle. Situated along the north shore of False Creek, Yaletown blends heritage industrial architecture with contemporary high-rise condo towers, offering some of the most distinctive real estate in Metro Vancouver. Residents enjoy the Seawall, David Lam Park, and a walkable urban village filled with upscale dining, fitness studios, and designer boutiques along Mainland and Hamilton streets. The neighbourhood is served by the Yaletown–Roundhouse Canada Line station, providing rapid transit access to downtown Vancouver, Richmond, and YVR. Yaletown condos command premium prices reflecting the neighbourhood\'s lifestyle, location, and prestige, making it a perennial favourite among professionals, downsizers, and international buyers.',
            ],
            [
                'place' => 'Coal Harbour',
                'city'  => 'Vancouver',
                'description' => 'Coal Harbour is Vancouver\'s most prestigious waterfront neighbourhood, occupying a prime position between the downtown financial district and Stanley Park. The neighbourhood is defined by its iconic marina, breathtaking views of the North Shore mountains, Burrard Inlet, and the Vancouver skyline. Real estate in Coal Harbour consists almost exclusively of luxury condominiums and penthouse suites in architecturally significant towers, making it one of the most exclusive markets in Canada. Residents have immediate access to the Coal Harbour Seawall, Harbour Green Park, and the Vancouver Convention Centre, with the Canada Line and West Coast Express nearby. The area attracts high-net-worth buyers, corporate executives, and international investors who value privacy, security, and world-class urban living. Average condo prices in Coal Harbour are among the highest in Metro Vancouver, reflecting its unmatched location and prestige.',
            ],
            [
                'place' => 'Kitsilano',
                'city'  => 'Vancouver',
                'description' => 'Kitsilano, affectionately known as "Kits," is one of Vancouver\'s most beloved westside neighbourhoods, celebrated for its beach culture, heritage homes, and vibrant community spirit. Stretching along the north shore of the Burrard Peninsula, Kitsilano is anchored by the iconic Kitsilano Beach and the outdoor Kits Pool, which draw residents and visitors throughout the summer months. The neighbourhood\'s real estate landscape encompasses a charming mix of character houses, heritage converted homes, half-duplexes, and low- to mid-rise condominiums along Broadway and 4th Avenue. Kitsilano\'s tree-lined streets are dotted with independent cafés, yoga studios, organic grocers, and boutique shops that reflect the community\'s active, health-conscious lifestyle. With excellent access to UBC, downtown Vancouver, and the future Broadway Subway extension, Kitsilano remains one of the most desirable and consistently high-value communities in Metro Vancouver.',
            ],
            [
                'place' => 'Downtown VW',
                'city'  => 'Vancouver',
                'description' => 'Downtown Vancouver West is the vibrant commercial and residential core of Metro Vancouver, encompassing the central business district, Robson Street shopping, the waterfront, and some of the city\'s highest-density residential real estate. The neighbourhood is defined by a dense mix of high-rise condominiums, luxury rentals, heritage lofts, and mixed-use towers catering to a cosmopolitan urban population. World-class restaurants, performing arts venues including the Queen Elizabeth Theatre and the Orpheum, major hotels, and an unrivalled retail corridor make Downtown VW one of Canada\'s most liveable urban cores. The Canada Line, Expo Line, and SeaBus provide exceptional transit access to Richmond, Burnaby, North Vancouver, and YVR. Downtown Vancouver West condos command strong prices driven by sustained demand from professionals, international buyers, and investors seeking high-yield rentals in one of North America\'s most globally recognized cities.',
            ],
            [
                'place' => 'Downtown VE',
                'city'  => 'Vancouver',
                'description' => 'Downtown Vancouver East encompasses the revitalized east side of Vancouver\'s city centre, including the historic Gastown district, Chinatown, and the evolving Railtown neighbourhood. Long undervalued relative to its western counterpart, Downtown VE has experienced significant gentrification and development activity, drawing creative industries, tech startups, restaurants, and boutique retail to its heritage brick streetscapes. Real estate includes character warehouse conversions, heritage lofts, newer concrete condo towers, and mixed-use residential buildings that appeal to artists, young professionals, and lifestyle-conscious buyers. The neighbourhood is served by the Expo Line\'s Stadium-Chinatown and Main Street-Science World stations, providing rapid transit throughout Metro Vancouver. Ongoing investment and redevelopment in Chinatown and along East Hastings continue to evolve Downtown VE\'s identity, making it one of Vancouver\'s most dynamic and value-driven real estate opportunities.',
            ],
            [
                'place' => 'West End VW',
                'city'  => 'Vancouver',
                'description' => 'The West End is Vancouver\'s most densely populated neighbourhood and one of Canada\'s great urban villages, situated between Stanley Park and downtown Vancouver along the English Bay shoreline. Defined by its high-rise apartment towers, low-rise character buildings, and tree-lined residential streets, the West End has been a cosmopolitan community since the 1960s and continues to evolve with new condo development. English Bay Beach, Sunset Beach, Denman Street\'s eclectic dining and retail scene, and immediate proximity to Stanley Park\'s 1,000 acres of old-growth forest define the West End lifestyle. The neighbourhood is served by multiple bus routes and is walkable to downtown Vancouver, Yaletown, and the Burrard SkyTrain station. West End condos offer a range of price points from entry-level studios to luxury suites, making it Vancouver\'s premier neighbourhood for walkable urban living at a variety of budgets.',
            ],
            [
                'place' => 'False Creek North',
                'city'  => 'Vancouver',
                'description' => 'False Creek North is a prestigious waterfront neighbourhood on the north shore of False Creek in downtown Vancouver, best known as the home of BC Place and Rogers Arena and the striking residential towers of Concord Pacific Place — one of the largest master-planned communities in Canadian real estate history. The neighbourhood offers exceptional high-rise condominiums with sweeping water, mountain, and city views, attracting professionals, downsizers, and international buyers seeking a premier urban lifestyle. The False Creek Seawall provides direct walking and cycling access to Yaletown, Science World, and Granville Island, while the Stadium-Chinatown and Main Street-Science World SkyTrain stations provide rapid transit connections. False Creek North combines sports and entertainment access with sophisticated waterfront living, making it one of downtown Vancouver\'s most compelling and distinctive real estate destinations.',
            ],
            [
                'place' => 'Fairview VW',
                'city'  => 'Vancouver',
                'description' => 'Fairview is a centrally located westside Vancouver neighbourhood nestled between Broadway and the False Creek shoreline, offering an appealing mix of urban convenience and residential calm. The neighbourhood\'s real estate ranges from mid-rise and high-rise condominiums along the Broadway corridor to character houses, half-duplexes, and boutique low-rise buildings on quieter side streets south of Broadway. Fairview is home to Vancouver General Hospital and a significant health sciences campus, making it a prime address for medical professionals and healthcare workers. The Broadway-City Hall and Broadway-Commercial SkyTrain stations and numerous bus routes along Broadway and Cambie provide excellent transit connectivity. South Granville\'s galleries, fine dining, and specialty retailers are within walking distance, while the False Creek Seawall offers recreational access to Science World, Granville Island, and beyond. Fairview remains one of Vancouver\'s most liveable and professionally oriented westside communities.',
            ],
            [
                'place' => 'Mount Pleasant VE',
                'city'  => 'Vancouver',
                'description' => 'Mount Pleasant East is one of Vancouver\'s most creative and rapidly evolving eastside neighbourhoods, celebrated for its thriving arts and tech scene, independent restaurants, coffee shops, and craft breweries. Situated on a gentle rise between Main Street and Commercial Drive, the neighbourhood has transitioned from a light-industrial heritage to become one of Vancouver\'s most sought-after communities for young professionals and urban families. Real estate in Mount Pleasant East includes character houses, heritage duplexes, newer townhomes, and a growing number of concrete condo towers along key arterials. The Main Street-Science World SkyTrain station and multiple bus routes along Main and Broadway provide excellent transit access to downtown Vancouver and the rest of the city. Mount Pleasant East\'s combination of authenticity, community spirit, and strong real estate appreciation makes it one of Vancouver\'s most exciting inner-city investment markets.',
            ],
            [
                'place' => 'Mount Pleasant VW',
                'city'  => 'Vancouver',
                'description' => 'Mount Pleasant West is a dynamic and culturally vibrant westside Vancouver neighbourhood straddling the Cambie Street corridor and Broadway, quickly transforming with the ongoing Broadway Subway extension. The neighbourhood blends a rich industrial and arts heritage with new concrete condo towers, boutique retail, and a burgeoning restaurant scene that has earned it recognition as one of Vancouver\'s most liveable urban communities. Real estate options range from heritage character homes and half-duplexes on residential side streets to new high-rise condo buildings along Cambie and Broadway. Proximity to Vancouver General Hospital, City Hall, and the evolving South Cambie health sciences precinct sustains strong rental demand from healthcare professionals and academics. The Broadway-City Hall Canada Line station and the incoming Broadway Subway stations reinforce Mount Pleasant West\'s position as one of Vancouver\'s most strategically located and investment-worthy real estate markets.',
            ],
            [
                'place' => 'Grandview Woodland',
                'city'  => 'Vancouver',
                'description' => 'Grandview-Woodland is one of East Vancouver\'s most vibrant and eclectic neighbourhoods, best known as the home of Commercial Drive — a beloved street of independent coffee shops, ethnic restaurants, vintage stores, and cultural venues that give the neighbourhood an irreplaceable urban character. The area\'s real estate mix includes character Craftsman and Victorian houses, heritage duplexes, low-rise apartments, and newer condo developments, appealing to artists, young professionals, and families drawn to the neighbourhood\'s authentic community spirit. Commercial-Broadway SkyTrain station — one of Metro Vancouver\'s busiest transit hubs — provides rapid access to downtown Vancouver, Burnaby, and the Expo and Millennium lines. Grandview-Woodland\'s mature tree canopy, lively street life, and strong neighbourhood identity make it one of Vancouver\'s most beloved eastside communities and a consistently active real estate market.',
            ],
            [
                'place' => 'Hastings Sunrise',
                'city'  => 'Vancouver',
                'description' => 'Hastings-Sunrise is an emerging East Vancouver neighbourhood attracting increasing attention from buyers and investors priced out of more expensive Vancouver communities. Stretching along East Hastings Street from Clark Drive to Boundary Road, the neighbourhood is characterized by affordable character houses, duplexes, and low-rise condos on tree-lined residential streets, punctuated by local commercial nodes with bakeries, cafés, hardware stores, and independent businesses. Hastings-Sunrise borders the PNE grounds and Hastings Park, providing access to the Pacific National Exhibition, the Playland amusement park, and Hastings Racecourse. Bus transit along Hastings provides connections to the Expo Line and downtown Vancouver. The neighbourhood\'s affordability relative to adjoining communities, strong community character, and proximity to both the waterfront and East Van amenities make Hastings-Sunrise one of Vancouver\'s most compelling value propositions in the current real estate market.',
            ],
            [
                'place' => 'Kerrisdale',
                'city'  => 'Vancouver',
                'description' => 'Kerrisdale is one of Vancouver\'s most prestigious and established westside neighbourhoods, known for its upscale village shopping district, heritage character homes, and long-standing reputation as a desirable family community. The neighbourhood\'s real estate is defined by substantial detached single-family homes, elegant heritage properties, and a growing number of luxury condominiums and townhouses catering to downsizers seeking to remain in one of Vancouver\'s finest areas. The Kerrisdale village on 41st Avenue offers independent boutiques, fine dining, gourmet grocery, and professional services in a charming pedestrian-friendly setting. Bus routes along 41st Avenue and Granville Street provide transit access to the Canada Line and UBC. Excellent public and private schools, including Point Grey Secondary and several sought-after elementary schools, make Kerrisdale one of Vancouver\'s top family destinations. Kerrisdale consistently commands among the highest real estate values on Vancouver\'s westside.',
            ],
            [
                'place' => 'South Granville',
                'city'  => 'Vancouver',
                'description' => 'South Granville is one of Vancouver\'s most sophisticated and artistic neighbourhoods, defined by the celebrated gallery and antique district along Granville Street between 5th and 16th avenues. The neighbourhood attracts art collectors, design professionals, and affluent buyers drawn to its cultural cachet and upscale residential character. Real estate in South Granville features impressive detached heritage homes, character mansions, half-duplexes, and a selection of boutique low-rise condominiums, making it one of Vancouver\'s most desirable westside addresses. Broadway\'s health sciences corridor and the Granville Street restaurant strip are both within walking distance, offering exceptional urban amenities. Bus transit along Granville and the Canada Line at Broadway-City Hall station provide convenient access to downtown Vancouver and YVR. South Granville appeals to discerning buyers who value culture, architecture, and a refined westside urban lifestyle in one of Vancouver\'s most storied communities.',
            ],
            [
                'place' => 'Marpole',
                'city'  => 'Vancouver',
                'description' => 'Marpole is a dense and increasingly popular neighbourhood at the southern end of Vancouver, situated along the Fraser River between the Granville Street and Oak Street bridges. Historically one of Vancouver\'s more affordable westside communities, Marpole is undergoing significant transformation with new condo and townhouse developments attracting young families and first-time buyers who value the combination of the Canada Line\'s Marine Drive station and the neighbourhood\'s improving amenity base. Real estate in Marpole ranges from older apartment buildings and character homes to newer concrete condos along Granville Street and Oak Street. The Marine Drive retail strip offers a growing selection of restaurants and services, while the nearby Marpole-Oakridge Community Centre provides recreational programming. YVR is approximately 20 minutes via the Canada Line, making Marpole particularly attractive to airport-area workers and frequent travellers.',
            ],
            [
                'place' => 'Oakridge VW',
                'city'  => 'Vancouver',
                'description' => 'Oakridge is a prime westside Vancouver neighbourhood centred around the transforming Oakridge Centre site, set to become one of Metro Vancouver\'s most ambitious mixed-use developments featuring residential towers, retail, office space, and parks upon a former shopping mall site. The neighbourhood is served by the Oakridge-41st Avenue Canada Line station, making it one of the most transit-convenient addresses in all of Vancouver. Current real estate includes established detached single-family homes on generous westside lots, older apartment buildings, and newer condos that will be complemented by thousands of additional units as the Oakridge redevelopment matures. Cambie Street\'s Corridor Plan has driven consistent new development throughout Oakridge, reinforcing its position as one of Vancouver\'s fastest-appreciating westside real estate markets. Excellent schools, including Eric Hamber Secondary, and proximity to Queen Elizabeth Park strengthen the neighbourhood\'s appeal to families.',
            ],
            [
                'place' => 'Point Grey',
                'city'  => 'Vancouver',
                'description' => 'Point Grey is one of Vancouver\'s most prestigious and storied westside neighbourhoods, home to the University of British Columbia and bordered by the Pacific Ocean, English Bay, and Pacific Spirit Regional Park. The neighbourhood\'s real estate is defined by some of Vancouver\'s most impressive and expensive single-family homes, including heritage mansions, custom contemporary residences, and landmark waterfront estates on streets like Northwest Marine Drive and Chancellor Boulevard. While detached homes dominate, a selection of character lowrises and condos along 10th Avenue and Sasamat Street serve apartment-focused buyers. Point Grey\'s proximity to UBC\'s academic and cultural resources, the Museum of Anthropology, Wreck Beach, and Jericho Beach gives it an unmatched combination of natural beauty and intellectual vitality. Point Grey consistently ranks among the highest-valued real estate markets in Metro Vancouver and Canada as a whole.',
            ],
            [
                'place' => 'West Point Grey',
                'city'  => 'Vancouver',
                'description' => 'West Point Grey is a serene and upscale westside Vancouver neighbourhood immediately adjacent to the UBC endowment lands, Pacific Spirit Regional Park, and the breathtaking Spanish Banks and Locarno Beach waterfront. The neighbourhood is characterized by large detached single-family homes on generously sized lots, many with views of English Bay, the North Shore mountains, or Burrard Inlet, making it one of Vancouver\'s most desirable and expensive residential addresses. Heritage character homes intermingle with newer luxury custom builds along quiet, tree-lined streets that give the neighbourhood an exclusive, private feel. West Point Grey Academy and Lord Byng Secondary attract families prioritizing academic excellence. Bus routes along 10th Avenue and Northwest Marine Drive connect to the broader Vancouver transit network. West Point Grey appeals to affluent families, academics, and high-net-worth buyers seeking the finest combination of natural beauty, privacy, and prestige that Vancouver real estate can offer.',
            ],
            [
                'place' => 'Sunset',
                'city'  => 'Vancouver',
                'description' => 'Sunset is a vibrant, multicultural East Vancouver neighbourhood south of Main Street, celebrated for its diverse community, authentic ethnic restaurants, and strong immigrant heritage anchored by South Asian, Chinese, Filipino, and Vietnamese communities. The area offers some of East Vancouver\'s most affordable detached home and duplex opportunities, making it a prime destination for first-time buyers seeking to enter the Vancouver real estate market. Real estate in Sunset includes older single-family homes, character duplexes, townhouses, and low-rise apartment buildings, typically on compact city lots. Main Street\'s commercial strip provides everyday retail and dining options, while the Canada Line\'s Marine Drive and Langara stations offer efficient transit to downtown Vancouver and YVR. Sunset\'s affordability within the City of Vancouver, combined with its rich cultural character and improving amenity base, makes it an increasingly attractive real estate market for value-conscious buyers.',
            ],
            [
                'place' => 'Killarney VE',
                'city'  => 'Vancouver',
                'description' => 'Killarney is an established residential neighbourhood in southeast Vancouver, offering some of the City of Vancouver\'s most accessible and family-friendly real estate. The neighbourhood is characterized by well-maintained detached homes, duplexes, and low-rise apartments on quiet, grid-pattern streets, with a predominantly East and South Asian community that brings excellent cultural amenities including authentic restaurants, grocery stores, and community organizations. Killarney Community Centre and Killarney Park provide recreation and green space for the neighbourhood\'s active family population. Major bus routes along 41st Avenue, Killarney Street, and Victoria Drive connect residents to the SkyTrain network. Relatively affordable by Vancouver standards, Killarney consistently appeals to families seeking detached home ownership within the city limits, strong public schools, and the convenience of established neighbourhood infrastructure at prices that remain more accessible than westside Vancouver communities.',
            ],
            [
                'place' => 'Victoria VE',
                'city'  => 'Vancouver',
                'description' => 'Victoria is a well-established East Vancouver neighbourhood anchored by the busy Victoria Drive commercial corridor, offering residents a practical and affordable urban lifestyle within the City of Vancouver. The neighbourhood\'s real estate consists primarily of older detached homes, duplexes, and low-rise apartment buildings that appeal to first-time buyers, families, and investors seeking income properties within the city. Victoria Drive\'s eclectic mix of Filipino restaurants, Vietnamese phở houses, grocery stores, and small businesses reflects the neighbourhood\'s rich multicultural character. Bus routes along Victoria Drive and 41st Avenue provide connections to the Commercial-Broadway and Main Street-Science World SkyTrain stations. Collingwood Neighbourhood House and several parks and schools serve the area\'s strong community. Victoria VE offers some of Vancouver\'s best value for buyers seeking entry-level detached or duplex properties within the city, making it a consistent focus for first-time buyers and investors.',
            ],

            // ── Richmond ─────────────────────────────────────────────────────────
            [
                'place' => 'Brighouse',
                'city'  => 'Richmond',
                'description' => 'Brighouse is Richmond\'s city centre neighbourhood, anchored by City Hall, the Richmond Centre mall, and a growing high-rise condo district built around the Brighouse Canada Line station. As Richmond\'s most transit-connected and commercially active subarea, Brighouse has experienced intense condo development over the past decade, with towers offering a range of suites from studio units to multi-bedroom residences. The neighbourhood\'s walkable urban core provides direct access to T&T Supermarket, a diverse array of Asian restaurants, banks, medical offices, and professional services along No. 3 Road — Richmond\'s main commercial spine. The Canada Line\'s Brighouse station connects residents to downtown Vancouver in under 25 minutes and YVR in under 10. Brighouse appeals strongly to young professionals, students at Kwantlen Polytechnic University\'s Richmond campus, and investors drawn to the neighbourhood\'s high rental demand and urban transit-oriented lifestyle.',
            ],
            [
                'place' => 'Steveston Village',
                'city'  => 'Richmond',
                'description' => 'Steveston Village is Richmond\'s most charming and historically significant neighbourhood, a picturesque fishing village on the southwestern tip of Lulu Island that has evolved into one of Metro Vancouver\'s most beloved lifestyle destinations. The village\'s boardwalk, working fishing docks, heritage cannery museum, independent restaurants, boutique shops, and seasonal farmers market draw residents and visitors alike year-round. Real estate in Steveston ranges from heritage character homes and bungalows to newer townhouses and low-rise condos, with waterfront and ocean-view properties commanding significant premiums. The neighbourhood is served by bus routes connecting to the Richmond-Brighouse Canada Line station. Garry Point Park and the Dyke Trail offer stunning outdoor recreational access along the shoreline. Steveston Village consistently appeals to families, downsizers, and lifestyle buyers who want the unique combination of small-town village charm, waterfront access, and Metro Vancouver convenience.',
            ],
            [
                'place' => 'McLennan',
                'city'  => 'Richmond',
                'description' => 'McLennan, also known as the Garden City area, is one of Richmond\'s most established and family-oriented residential neighbourhoods, located in the central part of the city between Garden City Road and No. 4 Road. The neighbourhood features a predominance of detached single-family homes and townhouses on spacious lots, many with well-maintained gardens reflecting the community\'s peaceful suburban character. McLennan residents benefit from proximity to Richmond\'s excellent school network, including Hugh Boyd Secondary, and several community centres and parks including the Aberdeen Community Centre. The No. 3 Road Canada Line corridor and Bridgeport are readily accessible by bus, while Highway 99 provides efficient connections to Vancouver, Delta, and the US border. McLennan\'s combination of residential space, good schools, and central Richmond location makes it a perennial favourite for families seeking quality suburban living in the Metro Vancouver market.',
            ],
            [
                'place' => 'Seafair',
                'city'  => 'Richmond',
                'description' => 'Seafair is a well-established and spacious residential neighbourhood in southwest Richmond, BC, known for its quiet streets, generous lot sizes, and proximity to the West Dyke Trail along the Strait of Georgia shoreline. The neighbourhood offers primarily detached single-family homes and some townhouse developments, appealing to families and established buyers seeking more space and a quieter lifestyle than Richmond\'s denser city centre nodes. Seafair\'s real estate benefits from relatively larger lots compared to other Richmond neighbourhoods, with some properties backing onto protected agricultural land or offering views across the dyke lands. Bus routes along Garden City and Williams Roads connect residents to the Canada Line\'s Brighouse and Lansdowne stations. The neighbourhood is also convenient to the West Richmond Community Centre and several well-regarded elementary schools. Seafair represents a solid and consistent family-focused real estate market within the City of Richmond.',
            ],
            [
                'place' => 'Terra Nova',
                'city'  => 'Richmond',
                'description' => 'Terra Nova is a prestigious master-planned residential community in the northwest corner of Richmond, BC, developed in the late 1990s and early 2000s as one of the city\'s last major residential land releases. The neighbourhood is defined by upscale single-family homes and executive townhouses on curving, traffic-calmed streets, many backing onto protected agricultural land or overlooking the Terra Nova Natural Area — a significant wetland bird sanctuary on the edge of the Fraser River. Real estate in Terra Nova commands among Richmond\'s highest prices, reflecting the neighbourhood\'s planned nature, quality of housing stock, and natural surroundings. The Terra Nova Rural Park provides an idyllic green escape, while bus routes connect residents to the Canada Line. Terra Nova\'s combination of planned community elegance, natural environment, and proximity to Steveston Village\'s amenities makes it one of Richmond\'s most desirable addresses for families and discerning buyers.',
            ],

            // ── Coquitlam ────────────────────────────────────────────────────────
            [
                'place' => 'Burke Mountain',
                'city'  => 'Coquitlam',
                'description' => 'Burke Mountain is Coquitlam\'s newest and fastest-growing master-planned community, situated on the lower slopes of Burke Mountain in the northeast corner of the city. Developed since the mid-2010s, the neighbourhood is defined by contemporary single-family homes, duplexes, townhouses, and an increasing number of low-rise and mid-rise condos built to modern standards with energy-efficient construction and thoughtful streetscaping. Burke Mountain\'s elevated terrain provides many homes with impressive valley and mountain views. The neighbourhood is connected to Coquitlam Centre and the Evergreen SkyTrain extension via bus, with further transit enhancements planned. Burke Mountain\'s trails, parks, and proximity to the Pinecone Burke Provincial Park provide exceptional outdoor recreational opportunities. The neighbourhood consistently attracts young families seeking new homes with good schools in a rapidly developing community that offers modern housing stock at pricing more accessible than comparable Metro Vancouver markets.',
            ],
            [
                'place' => 'Westwood Plateau',
                'city'  => 'Coquitlam',
                'description' => 'Westwood Plateau is one of Coquitlam\'s most prestigious and scenic residential communities, developed in the 1990s on a plateau above the city with panoramic views of the Fraser Valley, Mount Baker, and the North Shore mountains. The neighbourhood is characterized by executive single-family homes, elegant townhouses, and a small number of luxury condominiums, predominantly from quality builders of the era featuring generous floor plans and large lots. Westwood Plateau Golf and Country Club anchors the community and defines much of its upscale residential character. The neighbourhood is served by bus routes connecting to Lafarge Lake-Douglas and Coquitlam Central SkyTrain stations on the Evergreen Extension. Excellent schools including Dr. Charles Best Secondary, extensive trail networks, and a close-knit community atmosphere make Westwood Plateau consistently popular with established families and move-up buyers seeking quality and lifestyle within the Tri-Cities real estate market.',
            ],
            [
                'place' => 'Maillardville',
                'city'  => 'Coquitlam',
                'description' => 'Maillardville is Coquitlam\'s most historically significant neighbourhood and the oldest French-Canadian community west of Manitoba, offering a unique cultural heritage, Village Square district, and a strong sense of community identity. Situated in the southwest corner of Coquitlam adjacent to New Westminster, Maillardville features a mix of older character homes, post-war bungalows, newer townhouse developments, and mid-rise condos that provide some of the most affordable entry-level real estate in the Tri-Cities market. The neighbourhood\'s proximity to the Braid Street SkyTrain station on the Evergreen Extension allows quick transit access to Burnaby, New Westminster, and downtown Vancouver. Place Maillardville community centre, Mackin Park, and proximity to the Brunette River trail system offer excellent recreational amenities. Maillardville\'s combination of historical character, transit access, and affordability makes it a compelling choice for first-time buyers and investors in the Coquitlam real estate market.',
            ],
            [
                'place' => 'Scott Creek',
                'city'  => 'Coquitlam',
                'description' => 'Scott Creek is a well-established, family-oriented neighbourhood in central Coquitlam, BC, developed primarily in the 1980s and offering a mature suburban environment with a strong community infrastructure. The neighbourhood features a mix of detached single-family homes, townhouses, and some low-rise condos on quiet residential streets with excellent school catchments including Scott Creek Middle School and Dr. Charles Best Secondary. Scott Creek\'s central location within Coquitlam provides easy access to Coquitlam Centre\'s shopping and transit hub, including Coquitlam Central SkyTrain station on the Evergreen Extension. Large green spaces, including Mundy Park — one of the largest parks in the Tri-Cities — are within cycling distance. Scott Creek appeals to families seeking a well-rounded, established community with quality schools, green space, transit access, and solid detached home values at pricing generally more accessible than comparable communities in Vancouver or Burnaby.',
            ],
            [
                'place' => 'New Horizons',
                'city'  => 'Coquitlam',
                'description' => 'New Horizons is a vibrant and diverse residential neighbourhood in the heart of Coquitlam, BC, situated in close proximity to Coquitlam Centre mall, Lincoln SkyTrain station on the Evergreen Extension, and Town Centre Park — one of the region\'s premier urban parks. The neighbourhood features a broad mix of high-rise condos, mid-rise apartment buildings, townhouses, and some detached homes, making it one of Coquitlam\'s most transit-friendly and walkable communities. Town Centre Park\'s Lafarge Lake, sports fields, and recreation facilities provide exceptional green space amenity steps from residential towers. Coquitlam Centre provides extensive retail, dining, and services, with direct SkyTrain access to Burnaby and downtown Vancouver. New Horizons appeals to a diverse range of buyers including young professionals, families, students attending Kwantlen Polytechnic\'s nearby campus, and investors attracted by the neighbourhood\'s strong rental demand and continued development momentum.',
            ],

            // ── North Vancouver ──────────────────────────────────────────────────
            [
                'place' => 'Lynn Valley',
                'city'  => 'North Vancouver',
                'description' => 'Lynn Valley is one of North Vancouver\'s most beloved and family-centred neighbourhoods, known for its deep connection to the outdoors and proximity to the spectacular Lynn Canyon Park and Ecology Centre. The neighbourhood\'s real estate spans a wide range from modest older townhouses and condos to large executive single-family homes on generously sized lots, offering entry points for a broad range of buyers in the North Vancouver market. Lynn Valley Centre provides a walkable commercial hub with grocery, restaurants, and professional services at its heart. Bus routes connect residents to Lonsdale Quay and the SeaBus to downtown Vancouver. Lynn Valley Secondary and several excellent elementary schools serve the neighbourhood\'s predominantly family demographic. The trail networks connecting Lynn Canyon, Mount Fromme, and Seymour make Lynn Valley a top choice for outdoor enthusiasts who want world-class hiking, mountain biking, and nature access as part of their daily lives.',
            ],
            [
                'place' => 'Upper Lonsdale',
                'city'  => 'North Vancouver',
                'description' => 'Upper Lonsdale is a prestigious hillside neighbourhood in North Vancouver, BC, offering commanding views of Burrard Inlet, Vancouver Harbour, and the city skyline from many of its elevated residential streets. The neighbourhood is characterized by a mix of well-maintained older detached homes, newer custom residences, and some townhouse developments on the slopes of Mount Fromme. Upper Lonsdale\'s real estate market attracts established buyers and families drawn to the neighbourhood\'s exclusivity, natural setting, and outstanding view potential. The neighbourhood is served by bus routes along Lonsdale Avenue connecting to Lonsdale Quay and the SeaBus terminal for pedestrian access to downtown Vancouver. Proximity to Capilano University, Edgemont Village\'s boutique shopping, and extensive North Shore trail networks further enhances Upper Lonsdale\'s lifestyle appeal. It represents one of North Vancouver\'s strongest long-term value propositions for buyers seeking prestige, space, and views.',
            ],
            [
                'place' => 'Lynnmour',
                'city'  => 'North Vancouver',
                'description' => 'Lynnmour is a unique and increasingly desirable neighbourhood in North Vancouver, BC, situated between Lynn Creek, Seymour River, and the Trans-Canada Highway in the city\'s eastern sector. The area is undergoing significant redevelopment as part of the Lynn Creek Town Centre plan, which envisions a new urban node with mid-rise and high-rise residential, retail, and community amenities around a revitalized Lynn Creek District. Current real estate includes a mix of older townhouses, small detached homes, and newer low-rise condos that offer some of the more accessible price points on the North Shore. Bus routes connect Lynnmour to Park Royal, Lonsdale Quay, and Highway 1 interchange. The neighbourhood abuts the Lynn Canyon Ecology Centre, Seymour River Park, and the regional trail network, providing exceptional outdoor access. As development progresses, Lynnmour represents a compelling early-stage investment opportunity in one of North Vancouver\'s most actively transforming communities.',
            ],
            [
                'place' => 'Canyon Heights NV',
                'city'  => 'North Vancouver',
                'description' => 'Canyon Heights is a tranquil and highly desirable neighbourhood on the upper slopes of North Vancouver, BC, renowned for its proximity to Grouse Mountain, the Cleveland Dam, and the Capilano River Regional Park. The neighbourhood\'s real estate is dominated by larger detached single-family homes on spacious lots, many featuring mountain or forest views that reflect the area\'s exceptional natural setting. Canyon Heights\' upper elevation and forest surroundings give it a distinctly resort-like character within a well-established residential community. Canyon Heights Elementary and Handsworth Secondary — one of North Vancouver\'s top-ranked secondary schools — serve the neighbourhood\'s family-oriented demographic. Bus service connects residents to Edgemont Village\'s boutique retail and the broader North Shore transit network. Canyon Heights consistently attracts executive buyers, families prioritizing excellent schools, and outdoor enthusiasts seeking a North Shore lifestyle defined by mountain proximity and natural beauty.',
            ],

            // ── West Vancouver ───────────────────────────────────────────────────
            [
                'place' => 'Ambleside',
                'city'  => 'West Vancouver',
                'description' => 'Ambleside is the vibrant waterfront village heart of West Vancouver, BC, offering a sophisticated combination of seaside living, village-scale retail, and exceptional mountain views. The neighbourhood anchors the eastern end of West Vancouver along the scenic Ambleside seawall and park, attracting residents who value walkable ocean access, outdoor markets, and a relaxed yet upscale community atmosphere. Real estate in Ambleside encompasses low-rise condominiums, luxury apartments, heritage character homes, and newer executive townhouses, offering a range of options for downsizers, professionals, and buyers seeking an affluent North Shore lifestyle. The Park Royal shopping centre is minutes away, and the SeaBus Horseshoe Bay ferry service and Highway 1 provide connections to downtown Vancouver and beyond. Ambleside\'s combination of waterfront character, village amenity, and West Vancouver\'s prestigious school system — including West Vancouver Secondary — makes it one of the most desirable communities on the North Shore.',
            ],
            [
                'place' => 'Dundarave',
                'city'  => 'West Vancouver',
                'description' => 'Dundarave is a charming and affluent seaside village neighbourhood in West Vancouver, BC, situated along the Marine Drive waterfront between 24th and 26th Streets. The neighbourhood is celebrated for its elegant boutiques, upscale restaurants, artisan bakeries, and proximity to Dundarave Beach and the scenic West Vancouver Seawall. Real estate in Dundarave features a mix of luxury condominiums, heritage character homes, executive half-duplexes, and prestigious single-family residences that attract high-net-worth buyers seeking a refined coastal lifestyle within one of Metro Vancouver\'s most exclusive municipalities. The neighbourhood is served by bus routes along Marine Drive connecting to Park Royal and the Lions Gate Bridge. Dundarave\'s intimate village scale, community market, exceptional views of Burrard Inlet, and proximity to Cypress Mountain\'s skiing trails further establish it as one of West Vancouver\'s most coveted and consistently high-value real estate addresses.',
            ],
            [
                'place' => 'British Properties',
                'city'  => 'West Vancouver',
                'description' => 'British Properties is West Vancouver\'s most iconic and exclusive residential neighbourhood, a prestigious hillside community developed in the early 20th century on the forested slopes above Park Royal and Capilano Canyon. The neighbourhood is defined by some of Metro Vancouver\'s most spectacular estate homes, including gated custom residences, heritage mansions, and modern architectural masterpieces set on large lots with expansive views of Burrard Inlet, downtown Vancouver, and the Gulf Islands. British Properties consistently ranks among the highest-priced real estate markets in Canada, attracting high-net-worth individuals, corporate executives, and international buyers seeking the pinnacle of Vancouver-area luxury living. Capilano Golf and Country Club, Capilano Canyon Regional Park, and proximity to Cypress Mountain provide world-class recreational access. British Properties\' combination of privacy, prestige, natural grandeur, and legendary status in the Metro Vancouver real estate market is unmatched.',
            ],
            [
                'place' => 'Caulfeild',
                'city'  => 'West Vancouver',
                'description' => 'Caulfeild is one of West Vancouver\'s most picturesque and sought-after neighbourhoods, a master-planned community developed in the 1960s on the rocky waterfront promontories and forested hillsides of the municipality\'s western end. The neighbourhood\'s distinctive character is shaped by its winding, organically planned streets that follow the natural topography, creating a non-grid residential landscape unlike most suburban communities. Real estate in Caulfeild features spacious single-family homes ranging from mid-century original designs to recent custom rebuilds, many with exceptional ocean and island views. Caulfeild\'s Lighthouse Park — featuring old-growth Douglas fir forest and dramatic rocky coastline — is one of West Vancouver\'s greatest natural treasures. Caulfeild Village provides a convenient retail node with grocery and services. The neighbourhood consistently attracts established families, retirees, and nature-conscious buyers who value privacy, prestige, and an extraordinary natural setting within the City of West Vancouver.',
            ],

            // ── New Westminster ──────────────────────────────────────────────────
            [
                'place' => 'Uptown NW',
                'city'  => 'New Westminster',
                'description' => 'Uptown is New Westminster\'s emerging commercial and residential hub, situated on the plateau above the Downtown core and experiencing significant condominium and mixed-use development driven by proximity to the Uptown New Westminster commercial district and excellent SkyTrain access. The neighbourhood is served by the New Westminster and 22nd Street SkyTrain stations on the Expo Line, providing rapid transit to Burnaby and downtown Vancouver. Real estate in Uptown ranges from older apartment buildings and character homes to newer concrete condos along 6th Avenue and Royal Avenue. Columbia Square and several major retailers along McBride Boulevard provide everyday convenience, while the growing restaurant scene and arts facilities enhance the neighbourhood\'s urban appeal. Uptown\'s transit-rich location, improving amenities, and pricing that remains significantly below comparable communities in Vancouver and Burnaby make it a compelling choice for first-time buyers and urban investors in the New Westminster real estate market.',
            ],
            [
                'place' => 'Downtown NW',
                'city'  => 'New Westminster',
                'description' => 'Downtown New Westminster is a vibrant, historic urban centre on the south bank of the Fraser River, serving as the original capital of British Columbia and now one of Metro Vancouver\'s most transit-connected and culturally rich mid-size cities. The neighbourhood is served by the New Westminster SkyTrain station and the River Market at Westminster Quay, a waterfront public market offering stunning Fraser River views, local vendors, and a growing restaurant and retail scene. Real estate in Downtown NW includes high-rise condominiums, heritage lofts, older apartment buildings, and newer mixed-use towers, offering some of the most affordable urban real estate in the entire Metro Vancouver market. The Pattullo and Alex Fraser bridges and direct Expo Line access make Downtown NW highly connected to Surrey, Burnaby, and Vancouver. With an active arts scene, waterfront trails, and strong community pride, Downtown New Westminster is increasingly popular with young professionals and investors.',
            ],
            [
                'place' => 'Queensborough',
                'city'  => 'New Westminster',
                'description' => 'Queensborough is a unique and rapidly developing neighbourhood on Lulu Island in New Westminster, BC, connected to the mainland by the Queensborough Bridge and offering an interesting mix of industrial heritage and new residential development. The neighbourhood has seen substantial townhouse and single-family home construction in the past decade, attracting young families and first-time buyers seeking affordable ground-oriented housing with easy access to Metro Vancouver. Queensborough Landing, a major outlet shopping centre with big-box retail and restaurants, provides significant on-site commercial amenity. Highway 91A and the Queensborough Bridge connect residents to Burnaby, Delta, and Surrey quickly by car. While SkyTrain access requires a short drive or bus ride to nearby New Westminster stations, the neighbourhood\'s affordability advantage and growing family demographic make Queensborough one of the more value-driven real estate opportunities available to buyers seeking ground-level homes in Metro Vancouver.',
            ],

            // ── Langley ──────────────────────────────────────────────────────────
            [
                'place' => 'Willoughby Heights',
                'city'  => 'Langley',
                'description' => 'Willoughby Heights is one of the Fraser Valley\'s fastest-growing communities and Langley\'s most active real estate market, attracting thousands of new residents each year with its large-scale master-planned townhome and single-family developments. Situated in the Township of Langley just east of Langley City, the neighbourhood offers modern new construction at significantly lower prices than comparable Metro Vancouver communities, making it one of the top destinations for first-time buyers and growing families priced out of Burnaby or Surrey. Willoughby Heights benefits from the under-construction Surrey-Langley SkyTrain extension, which will dramatically improve transit connectivity to the existing Expo Line and the broader Metro Vancouver network. Highway 1 access via 200th Street is excellent, and nearby Willowbrook Shopping Centre provides extensive retail and services. The neighbourhood\'s combination of new housing, improving transit, and family-oriented community character drives sustained real estate demand.',
            ],
            [
                'place' => 'Walnut Grove',
                'city'  => 'Langley',
                'description' => 'Walnut Grove is a mature, family-oriented community in the Township of Langley, BC, developed primarily in the 1980s and 1990s and offering a well-established suburban lifestyle with excellent schools and recreational amenities. The neighbourhood features a mix of detached single-family homes, townhouses, and some condos along its main commercial corridors, with tree-lined residential streets giving it a polished, well-maintained character. Walnut Grove Secondary School and several highly regarded elementary schools serve the neighbourhood\'s strong family demographic. Highway 1 access at 200th Street provides excellent connections to Surrey, Abbotsford, Coquitlam, and Metro Vancouver employment centres. Walnut Grove Community Centre and several parks offer recreational programming. The neighbourhood\'s relative affordability, established community infrastructure, and highway connectivity make it one of Langley\'s most consistently popular and liquid real estate markets for families seeking detached home ownership in the eastern Metro Vancouver region.',
            ],
            [
                'place' => 'Fort Langley',
                'city'  => 'Langley',
                'description' => 'Fort Langley is one of the Lower Mainland\'s most cherished heritage communities, a charming village on the south bank of the Fraser River in the Township of Langley that is designated as a National Historic Site of Canada. The village\'s heritage downtown along Glover Road is lined with independent boutiques, art galleries, cideries, breweries, and acclaimed restaurants that draw visitors from across Metro Vancouver. Real estate in Fort Langley includes heritage character homes, newer custom-built residences, and an increasingly competitive market for both established properties and infill developments, commanding premium prices for a Langley address. Fort Langley\'s proximity to Kwantlen Park Secondary, Bedford Channel Park, and the Fraser River waterfront enhances its lifestyle appeal. While transit options are limited compared to urban centres, its unique heritage character, growing culinary scene, and Fraser River proximity make Fort Langley one of the most distinctive and desirable small-town real estate markets in the region.',
            ],

            // ── Maple Ridge ──────────────────────────────────────────────────────
            [
                'place' => 'West Central MR',
                'city'  => 'Maple Ridge',
                'description' => 'West Central is Maple Ridge\'s established urban core neighbourhood, situated along the Lougheed Highway corridor west of the town centre and offering a mix of older single-family homes, townhouses, and mid-rise condos alongside the city\'s growing commercial and retail activity. The neighbourhood provides convenient access to the West Coast Express commuter rail service at Maple Meadows station, connecting residents to Mission, Coquitlam, and downtown Vancouver. Lougheed Highway connects West Central residents to Pitt Meadows, Port Coquitlam, and the broader Metro Vancouver highway network. Several parks, schools, and community facilities serve the neighbourhood\'s family population. West Central MR offers some of Maple Ridge\'s most affordable entry-level real estate options including condos and townhouses, making it particularly popular with first-time buyers and investors seeking income properties within the city\'s most transit-accessible corridor.',
            ],
            [
                'place' => 'Silver Valley',
                'city'  => 'Maple Ridge',
                'description' => 'Silver Valley is a master-planned residential community on the forested foothills of Golden Ears Provincial Park in Maple Ridge, BC, offering a stunning natural backdrop and a strong emphasis on environmental stewardship and sustainable community design. Developed primarily since the 2000s, the neighbourhood features newer single-family homes, townhouses, and some low-rise condos built along winding, ecologically sensitive streetscapes that integrate natural creek systems and green corridors. Silver Valley\'s proximity to Golden Ears Provincial Park, the Alouette River, and an extensive trail network makes it an exceptional choice for nature-loving families and outdoor recreation enthusiasts. While public transit service is limited compared to more urbanized communities, Lougheed Highway and Golden Ears Way provide road connections to Maple Ridge town centre and the Golden Ears Bridge toward Pitt Meadows and South Surrey. Silver Valley appeals strongly to buyers seeking a natural, community-oriented lifestyle in a relatively new and well-planned neighbourhood.',
            ],

            // ── Delta ────────────────────────────────────────────────────────────
            [
                'place' => 'Ladner',
                'city'  => 'Delta',
                'description' => 'Ladner is the historic village heart of the City of Delta, BC, a charming waterfront community at the mouth of the Fraser River known for its distinctive character, strong agricultural heritage, and relaxed pace of life. The village centre along Elliott Street features heritage storefronts, local restaurants, marine services, and a Saturday farmers market that reflects Ladner\'s proud community identity. Real estate in Ladner includes heritage character homes, post-war bungalows, newer townhouse and condo developments, and some waterfront properties along the sloughs and the Fraser River. Highway 99 and the Massey Tunnel provide connections to Richmond and Vancouver, while the upcoming Massey Tunnel Replacement Bridge will further improve regional connectivity. Ladner is popular with retirees, families seeking a quieter suburban lifestyle, and buyers who value the combination of small-town charm, outdoor recreation, and access to Metro Vancouver at a price point well below the urban core.',
            ],
            [
                'place' => 'Tsawwassen',
                'city'  => 'Delta',
                'description' => 'Tsawwassen is the southernmost community in Metro Vancouver, a family-friendly seaside suburb in the City of Delta known for its ferry terminal — the primary gateway to Vancouver Island and the Gulf Islands — and the massive Tsawwassen Mills and Tsawwassen Commons retail centres. The neighbourhood offers predominantly detached single-family homes on generous lots, with a mix of older post-war houses and newer executive developments reflecting decades of steady suburban growth. Ocean and mountain views are available from many properties, and the Tsawwassen beach and dyke trail provide outstanding waterfront recreation. Highway 17 connects Tsawwassen to Delta\'s other communities and to Highway 99 for access to Vancouver and Richmond. The Tsawwassen First Nation\'s land provides an important and evolving component of new housing development in the area. Tsawwassen appeals to families, retirees, and buyers seeking a seaside suburban lifestyle at pricing more accessible than inner Metro Vancouver communities.',
            ],
            [
                'place' => 'N. Delta',
                'city'  => 'Delta',
                'description' => 'North Delta is a family-oriented suburban neighbourhood in the City of Delta, BC, situated between Surrey and the agricultural heartland of Delta immediately south of the Scott Road corridor. The area offers some of Metro Vancouver\'s most affordable detached single-family homes relative to lot size, attracting first-time buyers and growing families who value space, quieter streets, and strong community infrastructure. North Delta\'s real estate includes a range of older bungalows, split-level homes, and newer infill developments, with many properties featuring large yards that are increasingly rare at comparable price points closer to Vancouver. Scott Road provides convenient bus transit connections to the Scott Road SkyTrain station on the Expo Line and to Surrey and New Westminster. Sungod Recreation Centre, Watershed Park, and several excellent schools serve North Delta\'s established family population. North Delta\'s value proposition — spacious lots at accessible prices near the SkyTrain — makes it a consistent draw for value-conscious buyers in the Metro Vancouver market.',
            ],
            [
                'place' => 'Sunshine Hills Woods',
                'city'  => 'Delta',
                'description' => 'Sunshine Hills Woods is one of North Delta\'s most desirable and elevated residential communities, situated on a wooded ridge with scenic views and a quiet, leafy suburban character that sets it apart from the flatter, more grid-pattern streets below. The neighbourhood features predominantly detached single-family homes on generous lots, many backing onto forested green spaces and ravines that give the area a semi-rural feel within Metro Vancouver\'s urban fabric. Seaquam Secondary and several well-regarded elementary schools serve the neighbourhood\'s strong family demographic. Road access via 72nd Avenue and 116th Street connects Sunshine Hills Woods to Scott Road\'s commercial corridor and transit links toward the SkyTrain network. The neighbourhood\'s combination of natural setting, good schools, spacious properties, and relative affordability compared to Surrey and Burnaby makes Sunshine Hills Woods a highly regarded and consistently sought-after address in North Delta\'s real estate market.',
            ],

            // ── Port Coquitlam ───────────────────────────────────────────────────
            [
                'place' => 'Glenwood PQ',
                'city'  => 'Port Coquitlam',
                'description' => 'Glenwood is one of Port Coquitlam\'s most established and centrally located neighbourhoods, offering a practical and family-friendly residential environment within easy reach of the Port Coquitlam town centre and Westcoast Express station. The neighbourhood features a mix of detached single-family homes, duplexes, and some older townhouses on quiet grid-pattern streets, with real estate values that generally offer solid affordability relative to comparable communities in Coquitlam and Burnaby. Hyde Creek Recreation Centre and several parks and schools serve the neighbourhood\'s active family community. Major roads including Lougheed Highway and Mary Hill Bypass provide efficient connections to the Mary Hill interchange and Highway 1. Bus routes serve the neighbourhood\'s transit needs, with the West Coast Express offering a direct rail commute to downtown Vancouver during peak hours. Glenwood PQ represents a consistent and dependable real estate market for families and investors seeking established housing in the Tri-Cities.',
            ],
            [
                'place' => 'Lincoln Park PQ',
                'city'  => 'Port Coquitlam',
                'description' => 'Lincoln Park is a well-established and family-focused neighbourhood in central Port Coquitlam, BC, known for its spacious detached homes, mature tree canopy, and proximity to some of the Tri-Cities\' best recreational green spaces. The neighbourhood is adjacent to Gates Park and the Coquitlam River trail system, providing excellent walking, cycling, and outdoor recreation along the river corridor. Real estate in Lincoln Park features predominantly detached single-family homes from the 1970s and 1980s, with some newer townhouse infill developments, making it a solid choice for families seeking established housing with yard space. Pitt River Middle School and several elementary schools serve the neighbourhood\'s family demographic. Lougheed Highway and Coast Meridian Road provide road connections to Coquitlam, Pitt Meadows, and Highway 7. Lincoln Park PQ offers a dependable and community-oriented real estate market within one of the Tri-Cities\' most liveable established neighbourhoods.',
            ],
        ];

        foreach ($descriptions as $data) {
            DB::table('places')
                ->where('type', 'subarea')
                ->whereRaw('LOWER(place) = LOWER(?)', [$data['place']])
                ->whereRaw('LOWER(city) = LOWER(?)', [$data['city']])
                ->update(['description' => $data['description']]);
        }
    }
}
