@extends('frontend.layouts.default_mobile')
@section('title'){{ $metaTitle }}@endsection
@section('meta_description'){{ $metaDesc }}@endsection
@section('meta')
<link rel="canonical" href="{{ $canonical }}">
<meta name="robots" content="noindex,follow">
<meta property="og:title" content="{{ $metaTitle }}">
<meta property="og:description" content="{{ $metaDesc }}">
<meta property="og:url" content="{{ $canonical }}">
<meta property="og:type" content="website">
@endsection
@section('content')
@include('frontend.includes.header')

<div class="page-main" style="margin-top:66px;padding:28px 0 0;">
    <div class="container">
        <nav aria-label="breadcrumb" style="margin-bottom:10px;">
            <ol class="breadcrumb" style="background:none;padding:0;margin:0;font-size:13px;">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">New Listings in {{ $city }}</li>
            </ol>
        </nav>
        <h1 style="font-size:24px;font-weight:700;margin-bottom:6px;color:#2c2c2c;">
            New Listings This Week in {{ $city }}, BC
        </h1>
        <p style="font-size:14px;color:#666;max-width:780px;line-height:1.7;margin-bottom:8px;">
            MLS® listings added to the {{ $city }} market in the last 7 days.
            @if($totalCount > 0)
                <strong>{{ number_format($totalCount) }} {{ $totalCount === 1 ? 'listing' : 'listings' }}</strong> added this week.
            @endif
            Updated daily.
        </p>
        <div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:6px;">
            <a href="/price-reductions/{{ $citySlug }}" style="font-size:12px;color:#2c6fad;text-decoration:none;">Price Reductions →</a>
            <a href="/sold-over-asking/{{ $citySlug }}" style="font-size:12px;color:#2c6fad;text-decoration:none;">Sold Over Asking →</a>
            <a href="/market-update/{{ $citySlug }}" style="font-size:12px;color:#2c6fad;text-decoration:none;">Monthly Updates →</a>
        </div>
    </div>
</div>

<div class="container" style="padding-bottom:40px;">

    @if($listings->isEmpty())
    <div class="row" style="margin-top:22px;">
        <div class="col-md-12">
            <div style="background:#f7f4ef;border-left:4px solid #ccc;border-radius:4px;padding:14px 18px;font-size:14px;color:#666;">
                No new listings were added in <strong>{{ $city }}</strong> in the last 7 days. Check the <a href="/market-update/{{ $citySlug }}" style="color:#2c6fad;">monthly market update</a> for broader trends.
            </div>
        </div>
    </div>
    @else
    <div class="row" style="margin-top:22px;">
        @foreach($listings as $listing)
        <div class="col-md-4 col-sm-6" style="margin-bottom:22px;">
            @include('frontend.includes.featured_listing_tile', ['listing' => $listing])
        </div>
        @endforeach
    </div>
    @if($totalCount > $listings->count())
    <div class="row">
        <div class="col-md-12" style="text-align:center;margin-top:8px;">
            <p style="font-size:14px;color:#888;">Showing {{ $listings->count() }} of {{ number_format($totalCount) }} new listings.
                <a href="/{{ strtolower(str_replace(' ','-',$city)) }}-for-sale" style="color:#2c6fad;margin-left:6px;">Browse all {{ $city }} listings →</a>
            </p>
        </div>
    </div>
    @endif
    @endif

    {{-- Email alert signup --}}
    <div class="row" style="margin-top:30px;">
        <div class="col-md-8 col-md-offset-2">
            @include('frontend.includes.market_intel_alert_widget', ['city' => $city, 'citySlug' => $citySlug, 'source' => 'new_listings'])
        </div>
    </div>

    {{-- Internal links --}}
    <div class="row" style="margin-top:24px;">
        <div class="col-md-12">
            <div style="background:#f7f4ef;border-radius:6px;padding:14px 18px;font-size:13px;color:#555;">
                <strong>Related:</strong>
                <a href="/search-listings/{{ $citySlug }}" style="margin-left:12px;color:#2c6fad;">All {{ $city }} Listings →</a>
                <a href="/market-report/{{ $citySlug }}" style="margin-left:12px;color:#2c6fad;">Market Reports →</a>
                <a href="/market-stats/{{ $citySlug }}" style="margin-left:12px;color:#2c6fad;">Market Stats →</a>
            </div>
        </div>
    </div>
</div>

<div class="listings-disclaimer">
    <div class="container">
        <p>Last Update: {{ \Carbon\Carbon::now()->format('m/d/Y') }} &nbsp;&nbsp;<strong>Disclaimer:</strong> Listing data is based in whole or in part on data generated by the Real Estate Board of Greater Vancouver and Fraser Valley Real Estate Board which assumes no responsibility for its accuracy.</p>
    </div>
</div>

@include('frontend.includes.hani_bubble')
@include('frontend.includes.footer_links')
@include('frontend.includes.footer')
@endsection
