@extends('frontend.layouts.default_mobile')
@section('title'){{ $metaTitle }}@endsection
@section('meta_description'){{ $metaDesc }}@endsection
@section('meta')
<link rel="canonical" href="{{ $canonical }}">
<meta name="robots" content="noindex,follow">
<meta property="og:title" content="{{ $metaTitle }}">
<meta property="og:description" content="{{ $metaDesc }}">
<meta property="og:url" content="{{ $canonical }}">
@endsection
@section('content')
@include('frontend.includes.header')

<div class="page-main" style="margin-top:66px;padding:28px 0 0;">
    <div class="container">
        <nav aria-label="breadcrumb" style="margin-bottom:10px;">
            <ol class="breadcrumb" style="background:none;padding:0;margin:0;font-size:13px;">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Price Reductions in {{ $city }}</li>
            </ol>
        </nav>
        <h1 style="font-size:24px;font-weight:700;margin-bottom:6px;color:#2c2c2c;">
            Price Reductions in {{ $city }}, BC
        </h1>
        <p style="font-size:14px;color:#666;max-width:780px;line-height:1.7;margin-bottom:8px;">
            Active MLS® listings in {{ $city }} with a price reduction in the last 14 days. Prices updated from MLS® daily.
        </p>
        <div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:6px;">
            <a href="/new-listings/{{ $citySlug }}" style="font-size:12px;color:#2c6fad;text-decoration:none;">New This Week →</a>
            <a href="/sold-over-asking/{{ $citySlug }}" style="font-size:12px;color:#2c6fad;text-decoration:none;">Sold Over Asking →</a>
            <a href="/market-update/{{ $citySlug }}" style="font-size:12px;color:#2c6fad;text-decoration:none;">Monthly Updates →</a>
        </div>
    </div>
</div>

<div class="container" style="padding-bottom:40px;">

    @if($listings->isEmpty())
    <div class="row" style="margin-top:22px;">
        <div class="col-md-12">
            <div style="background:#f7f4ef;border-left:4px solid #ccc;border-radius:4px;padding:14px 18px;font-size:14px;color:#666;">
                No price reductions found in <strong>{{ $city }}</strong> in the last 14 days. Check back soon or browse <a href="/search-listings/{{ $citySlug }}" style="color:#2c6fad;">all {{ $city }} listings</a>.
            </div>
        </div>
    </div>
    @else
    <div class="row" style="margin-top:22px;">
        @foreach($listings as $listing)
        @php
        $reduction     = ($listing->prev_price ?? 0) - ($listing->listprice_2 ?? 0);
        $reductionPct  = ($listing->prev_price > 0 && $reduction > 0)
                         ? round($reduction / $listing->prev_price * 100, 1)
                         : 0;
        @endphp
        <div class="col-md-4 col-sm-6" style="margin-bottom:22px;">
            <div style="position:relative;">
                @if($reduction > 0)
                <div style="position:absolute;top:0;left:0;z-index:10;background:#e74c3c;color:#fff;font-size:11px;font-weight:700;padding:4px 8px;border-radius:4px 0 4px 0;line-height:1.3;">
                    ▼ ${{ number_format($reduction) }} ({{ $reductionPct }}% off)
                </div>
                @endif
                @include('frontend.includes.featured_listing_tile', ['listing' => $listing])
            </div>
        </div>
        @endforeach
    </div>
    @endif

    {{-- Email alert signup --}}
    <div class="row" style="margin-top:30px;">
        <div class="col-md-8 col-md-offset-2">
            @include('frontend.includes.market_intel_alert_widget', ['city' => $city, 'citySlug' => $citySlug, 'source' => 'price_reductions'])
        </div>
    </div>

    {{-- Internal links --}}
    <div class="row" style="margin-top:24px;">
        <div class="col-md-12">
            <div style="background:#f7f4ef;border-radius:6px;padding:14px 18px;font-size:13px;color:#555;">
                <strong>Related:</strong>
                <a href="/search-listings/{{ $citySlug }}" style="margin-left:12px;color:#2c6fad;">All {{ $city }} Listings →</a>
                <a href="/market-report/{{ $citySlug }}" style="margin-left:12px;color:#2c6fad;">Market Reports →</a>
                <a href="/market-stats/{{ $citySlug }}" style="margin-left:12px;color:#2c6fad;">Market Stats →</a>
            </div>
        </div>
    </div>
</div>

<div class="listings-disclaimer">
    <div class="container">
        <p>Last Update: {{ \Carbon\Carbon::now()->format('m/d/Y') }} &nbsp;&nbsp;<strong>Disclaimer:</strong> Listing data is based in whole or in part on data generated by the Real Estate Board of Greater Vancouver and Fraser Valley Real Estate Board which assumes no responsibility for its accuracy.</p>
    </div>
</div>

@include('frontend.includes.hani_bubble')
@include('frontend.includes.footer_links')
@include('frontend.includes.footer')
@endsection
