<?php
$agents = array (
  0 => 
  array (
    'first' => 'Les',
    'last' => 'Twarog',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/les.jpg',
    'languages' => 'English, Polskie ',
    'tel' => '604-245-1041',
    'email' => 'les@bccondosandhomes.com',
    'video' => 'https://vimeo.com/698496463',
    'visible' => true,
  ),
  1 => 
  array (
    'first' => 'Andrew',
    'last' => 'Do',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/andrew.jpg',
    'languages' => 'English',
    'tel' => '778-654-7087',
    'email' => 'andrew@bccondos.net',
    'video' => ' https://www.loom.com/share/fec4c3b671344f64b89f369ef9d43773',
    'visible' => true,
  ),
  2 => 
  array (
    'first' => 'Jenny',
    'last' => 'Wu',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta_jenny-wu.jpg',
    'languages' => 'null',
    'tel' => NULL,
    'email' => 'jennywu@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  3 => 
  array (
    'first' => 'Denean',
    'last' => 'Arnold',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/denean.jpg',
    'languages' => 'English',
    'tel' => '604-229-8526',
    'email' => 'denean@bccondosandhomes.com',
    'visible' => true,
  ),
  4 => 
  array (
    'first' => 'Estelle',
    'last' => 'Luoma',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/Estelle.jpg',
    'languages' => 'English',
    'tel' => '604-332-7624',
    'email' => 'estelle@bccondosandhomes.com',
    'visible' => true,
  ),
  5 => 
  array (
    'first' => 'Bal',
    'last' => 'Virk',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/bal-virk.jpg',
    'languages' => 'English, ਪੰਜਾਬੀ',
    'tel' => '604-265-9065',
    'email' => 'bal@bccondosandhomes.com',
    'visible' => true,
  ),
  6 => 
  array (
    'first' => 'Michael',
    'last' => 'Gibson',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/michael-gibson.jpg',
    'languages' => 'English',
    'tel' => '778-653-3723',
    'email' => 'michael@bccondos.net',
    'visible' => true,
  ),
  7 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/brent.jpg',
    'languages' => 'English',
    'tel' => '604-265-7235',
    'email' => 'brent@bccondosandhomes.com',
    'video' => 'https://www.loom.com/share/2bb5398ae4fc4609b7f6e44394eebb20',
    'visible' => true,
  ),
  8 => 
  array (
    'first' => 'Thai',
    'last' => 'Do',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/ThaiDo.jpg',
    'languages' => 'English',
    'tel' => '604-828-2901',
    'email' => 'thai@bccondosandhomes.com',
    'visible' => true,
  ),
  9 => 
  array (
    'first' => 'Gerry',
    'last' => 'Kainth',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/gerry.jpg',
    'languages' => 'English, ਪੰਜਾਬੀ ',
    'tel' => '604-537-6947',
    'email' => 'gerry@bccondosandhomes.com',
    'visible' => true,
  ),
  10 => 
  array (
    'first' => 'Fateh',
    'last' => 'Boparai',
    'profile_image' => 'https://www.bccondosandhomes.com/frontend/images/teamagents/fateh.png',
    'languages' => 'English, ਪੰਜਾਬੀ',
    'tel' => '604-337-1364',
    'email' => 'fateh@bccondosandhomes.com',
    'visible' => true,
  ),
  11 => 
  array (
    'first' => 'Denean Test',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta_denean-test-arnold.jpg',
    'languages' => 'English',
    'tel' => '604-229-8526',
    'email' => 'denean@bccondosandhomes.com',
    'video' => '',
    'visible' => true,
  ),
  12 => 
  array (
    'first' => 'Test',
    'last' => 'Arnold Test',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta_test-arnold-test.jpg',
    'languages' => 'English',
    'tel' => '604-229-8526',
    'email' => 'denean@bccondosandhomes.com',
    'video' => '',
    'visible' => true,
  ),
  13 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta_.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  14 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta_brent-arnold.jpg',
    'languages' => 'null',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  15 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta_brent-arnold.jpg',
    'languages' => 'null',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  16 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'null',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  17 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  18 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  19 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  20 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  21 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'null',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  22 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  23 => 
  array (
    'first' => NULL,
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  24 => 
  array (
    'first' => '5645',
    'last' => NULL,
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-5645.jpg',
    'languages' => NULL,
    'tel' => NULL,
    'email' => NULL,
    'video' => '',
    'visible' => true,
  ),
  25 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'null',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  26 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'English',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  27 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'English',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  28 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'English',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  29 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'English',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  30 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'English',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
  31 => 
  array (
    'first' => 'Brent',
    'last' => 'Arnold',
    'profile_image' => 'https://v2.bccondosandhomes.com/frontend/images/teamagents/ta-brent-arnold.jpg',
    'languages' => 'English',
    'tel' => NULL,
    'email' => 'brent@bccondos.net',
    'video' => '',
    'visible' => true,
  ),
);
return isset($_GET['show_all_agents']) ? $agents : array_filter($agents, fn($a) => $a['visible']??true);